In [3]:
import torch
import torch.nn.functional as F

data = ".abcd"

stoi = { char:i for i,char in enumerate(data)}
itos = { i:char for i,char in enumerate(data)}

In [20]:
example = "c"
#. -> c
xenc = F.one_hot(torch.tensor([0]), num_classes=5).float()
print(xenc)

tensor([[1., 0., 0., 0., 0.]])


In [22]:

W = torch.tensor(
    [

[ 0.2963, 1.1951, 0.7433, -0.1034, -0.6192],

[ 2.6439, 1.7843, 0.2086, 0.5000, 0.4406], 

[-0.6386, 0.2266, -0.0906, -0.3895, -0.2717],

[-0.2562, -0.7472, -0.8306, -1.2820, 0.2468],

[-1.3791, -1.8291, -0.4827, 0.2922, 0.4291]

]
    , requires_grad=True)

In [23]:
logits = xenc @ W
print(logits)
counts = logits.exp()
probs = counts / counts.sum(1, keepdims=True) 
print(probs) 

tensor([[ 0.2963,  1.1951,  0.7433, -0.1034, -0.6192]], grad_fn=<MmBackward0>)
tensor([[0.1642, 0.4033, 0.2567, 0.1101, 0.0657]], grad_fn=<DivBackward0>)


In [24]:
loss = -probs[torch.arange(1), [3]].log().mean()
print(loss)

tensor(2.2065, grad_fn=<NegBackward0>)


In [25]:
loss.backward()

In [26]:
print(W.grad.data)

tensor([[ 0.1642,  0.4033,  0.2567, -0.8899,  0.0657],
        [ 0.0000,  0.0000,  0.0000, -0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000, -0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000, -0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000, -0.0000,  0.0000]])


In [27]:
W.data += -50 * W.grad
print(W)

tensor([[ -7.9124, -18.9708, -12.0919,  44.3925,  -3.9053],
        [  2.6439,   1.7843,   0.2086,   0.5000,   0.4406],
        [ -0.6386,   0.2266,  -0.0906,  -0.3895,  -0.2717],
        [ -0.2562,  -0.7472,  -0.8306,  -1.2820,   0.2468],
        [ -1.3791,  -1.8291,  -0.4827,   0.2922,   0.4291]],
       requires_grad=True)


In [29]:
xenc = F.one_hot(torch.tensor([0]), num_classes=5).float()
print(xenc)
logits = xenc @ W
print(logits)
counts = logits.exp()
probs = counts / counts.sum(1, keepdims=True) 
print(probs) 

tensor([[1., 0., 0., 0., 0.]])
tensor([[ -7.9124, -18.9708, -12.0919,  44.3925,  -3.9053]],
       grad_fn=<MmBackward0>)
tensor([[1.9243e-23, 3.0316e-28, 2.9453e-25, 1.0000e+00, 1.0581e-21]],
       grad_fn=<DivBackward0>)
