In [9]:
import torch
import torch.nn.functional as F

data = ".abcd"

stoi = { char:i for i,char in enumerate(data)}
itos = { i:char for i,char in enumerate(data)}

In [10]:
#example = "c"
#. -> c
xenc = F.one_hot(torch.tensor([0,3]), num_classes=5).float()
print(xenc)

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.]])


In [11]:
#-0.1034 -> -0.8899
h = .5
W = torch.tensor(
    [

        [ 0.2963 , 1.1951, 0.7433 , -0.1034, -0.6192],
        [ 2.6439, 1.7843, 0.2086, 0.5000, 0.4406], 
        [-0.6386, 0.2266, -0.0906, -0.3895, -0.2717],
        [-0.2562, -0.7472, -0.8306, -1.2820, 0.2468],
        [-1.3791, -1.8291, -0.4827, 0.2922, 0.4291]

]
    , requires_grad=True)

In [8]:
reg = .01 * (W**2).mean()

W.grad = None
reg.backward()
print(W.grad.data)

tensor([[ 2.3704e-04,  9.5608e-04,  5.9464e-04, -8.2720e-05, -4.9536e-04],
        [ 2.1151e-03,  1.4274e-03,  1.6688e-04,  4.0000e-04,  3.5248e-04],
        [-5.1088e-04,  1.8128e-04, -7.2480e-05, -3.1160e-04, -2.1736e-04],
        [-2.0496e-04, -5.9776e-04, -6.6448e-04, -1.0256e-03,  1.9744e-04],
        [-1.1033e-03, -1.4633e-03, -3.8616e-04,  2.3376e-04,  3.4328e-04]])


In [6]:
for i  in range(1):
    
    logits = xenc @ W
    counts = logits.exp()
    probs = counts / counts.sum(1, keepdims=True) 
    loss = -probs[[0,1], [3, 1]].log().mean() + .01 * (W**2).mean()

    #current scenerio probability multiplication-> - log(liklihood) is equals to loss
    
    W.grad = None
    loss.backward()
    W.data += -5 * W.grad

print(W.data)
print(W.grad.data)

tensor([[-0.1153,  0.1820,  0.0986,  2.1218, -0.7810],
        [ 2.6333,  1.7772,  0.2078,  0.4980,  0.4388],
        [-0.6360,  0.2257, -0.0902, -0.3879, -0.2706],
        [-0.8522,  1.3904, -1.1634, -1.4909, -0.7415],
        [-1.3736, -1.8218, -0.4808,  0.2910,  0.4274]])
tensor([[ 8.2324e-02,  2.0262e-01,  1.2895e-01, -4.4504e-01,  3.2365e-02],
        [ 2.1151e-03,  1.4274e-03,  1.6688e-04,  4.0000e-04,  3.5248e-04],
        [-5.1088e-04,  1.8128e-04, -7.2480e-05, -3.1160e-04, -2.1736e-04],
        [ 1.1921e-01, -4.2752e-01,  6.6569e-02,  4.1784e-02,  1.9766e-01],
        [-1.1033e-03, -1.4633e-03, -3.8616e-04,  2.3376e-04,  3.4328e-04]])


          [ 0.2963 , 1.1951, 0.7433 , -0.1034, -0.6192],
       NC [ 2.6439, 1.7843, 0.2086, 0.5000, 0.4406], 
       NC [-0.6386, 0.2266, -0.0906, -0.3895, -0.2717],
          [-0.2562, -0.7472, -0.8306, -1.2820, 0.2468],
       NC [-1.3791, -1.8291, -0.4827, 0.2922, 0.4291]

-----------------------------------------------------------------

        [-1.0960, -0.9979, -1.0235,  6.0266, -1.3971],
        [ 2.6439,  1.7843,  0.2086,  0.5000,  0.4406],
        [-0.6386,  0.2266, -0.0906, -0.3895, -0.2717],
        [-1.9169,  5.1455, -2.0336, -2.1833, -1.8809],
        [-1.3791, -1.8291, -0.4827,  0.2922,  0.4291]

In [ ]:
sum([-8.2720e-05, -0.4450])

In [ ]:

formatted_number = "{:.10f}".format(-4.4504e-01)
print(formatted_number)
formatted_number = "{:.10f}".format(-8.2720e-05)
print(formatted_number)

In [ ]:
print(f"{-4.4504e-01}")

In [ ]:
xenc = F.one_hot(torch.tensor([0]), num_classes=5).float()
print(xenc)
logits = xenc @ W
print(logits)
counts = logits.exp()
probs = counts / counts.sum(1, keepdims=True) 
print(probs) 